version: '3.3'

services:
  web:
    build: .
    ports:
      - "9111:80"  # Modification ici pour spécifier l'adresse IP
    volumes:
      - .:/var/www/html/
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8888:80"  # Modification ici pour spécifier l'adresse IP
    depends_on:
      - db

volumes:
  dbdata:
